Collegion/urls.py
from django.contrib import admin
from django.urls import path, include
from Collegion_Backend import views
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView
from Collegion import settings
from chat_room.views import get_messages, send_messages
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    #path('logout/', logout,  name='logout'),
    path('', views.index, name='index'),
    path('', views.index, name='/accounts/login/'),
    path('register/', views.register_view, name='register'),
    path('chat/', include('Collegion_Backend.urls')),
     # URL form : "/api/messages/1/2"
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),  # For GET request.
    # URL form : "/api/messages/"
    path('api/messages/', views.message_list, name='message-list'),   # For POST
    # URL form "/api/users/1"
    path('api/users/<int:pk>', views.user_list, name='user-detail'),      # GET request for user with id
    path('api/users/', views.user_list, name='user-list'),    # POST for new user and GET for all users list
    path('chat/room/', include('chat_room.urls')),
    path('api/messages/<int:chatroom_id>/', get_messages, name='chat-room-messages'),
    path('api/chat-room/send-messages/', send_messages, name='chat-room-send=messages'),
    path('verification/', include('verify_email.urls')),
]

Collegion_Backend/urls.py
from django.urls import path
import Collegion_Backend.views as views

app_name = 'Collegion_Backend'


urlpatterns = [
    path('', views.chat_view, name='chats'),
    path('<int:sender>/<int:receiver>/', views.message_view, name='message_view'),
    path('add-dm-form/', views.add_dm_user_form, name="add-dm-user-form"),
    path('dm-add/<int:user_id>/', views.dm_add, name="dm_add"),
]

chat_room/urls.py
from django.urls import path
from .views import create_chat_room, delete_chat_room, message_chat_view, anonymous_handle, \
    remove_from_chat_room, add_user_form, add_user

app_name = 'chat_room'

urlpatterns = [
    path('<int:chatroom_id>/', message_chat_view, name='message-chatrooms'),
    path('create/', create_chat_room, name='create-chatroom'),
    path('addUser/<int:group_id>/<int:user_to_add_id>/', add_user, name='add-user'),
    path('addUserForm/<int:group_id>/', add_user_form, name='add-to-group'),
    path('remove-user/<int:room_id>/', remove_from_chat_room, name='remove-from-group'),
    path('anonymous/', anonymous_handle, name='anonymous'),
]

Collegion_Backend/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from chat_room.models import ChatRoom


class DMMessage(models.Model):
     sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
     receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver', null=True)
     message = models.CharField(max_length=1200)
     timestamp = models.DateTimeField(auto_now_add=True)
     is_read = models.BooleanField(default=False)

     def __str__(self):
           return self.message
     class Meta:
           ordering = ('timestamp',)


class GroupMessage(models.Model):
    is_read = models.ManyToManyField(User, related_name="is_read_group")
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=1200)
    chat_room = models.ForeignKey(ChatRoom, on_delete=models.SET_NULL, related_name='chat_room', null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_sender')
    anonymous = models.BooleanField(default=False)
    display_name = models.CharField(max_length=40, default="")


    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dm_users = models.ManyToManyField(User, related_name="dm_users")
    is_anonymous = models.BooleanField(default=False)
    anonymous_name = models.CharField(max_length=40, default="")

    # this method called for admin panel
    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

chat_room/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class ChatRoom(models.Model):
    name = models.CharField(max_length=50, null=True)
    create_date = models.DateField(default=datetime.date.today)
    member = models.ManyToManyField(User, related_name="member")
    creator = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name="creator")

templates/chat/add-dm.html
{% extends 'chat/chat.html' %}
{% block content %}

<form method="post" id="add-user-form" class="form-group">
       <div class="row">
           <input type="text" placeholder="Search by name, username" name="search" style="width: 210px">
           <input type="submit" name="btn-search" class="btn btn-success" style="background-color:#7289da;" value="Search">

       </div>
       {% for user in search_users %}
         <a href="/chat/dm-add/{{user.id}}/" id="user_card">
             <li class="list-group-item list-group-item-action user-list">
                <p>@{{user.username}}</p>
             </li>
         </a>
      {% endfor %}
</form>

{% endblock %}

templates/chat/add-to-group.html
{% extends 'chat/chat.html' %}
{% block content %}

<form method="post" id="add-user-form" class="form-group">
       <div class="row">
           <input type="text" placeholder="Search by name, username" name="search" style="width: 210px">
           <input type="submit" name="btn-search" class="btn btn-success" style="background-color:#7289da;" value="Search">

       </div>
       {% for user in search_users %}
         <a href="/chat/room/addUser/{{group}}/{{user.id}}/" id="user_card">
             <li class="list-group-item list-group-item-action user-list">
                 <p>@{{user.username}}</p>
             </li>
         </a>
      {% endfor %}
</form>

{% endblock %}

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="background-title">
    <div class="nav-wrapper container">
      <a href="" class="brand-logo" style="color:#6ca9e6;">Collegion</a>
      <ul id="nav-mobile" class="right">
          <li><a href="" style="color:#6ca9e6;">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}" style="color:#6ca9e6;"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
<div class="section" style="height: 80vh">
<div class="row">
    <div class="col s3">
    <div class="card background-title">
        <div class="background-title chatrooms">
<!--            purple #800080-->
            <h5 class="group-chat-label text-color">Chatrooms</h5>
            <div class="tooltip-container">
                <div class="tooltip">
                    {% if request.user.profile.is_anonymous %}
                        <span class="tooltiptext">Anonymous Off</span>
                        <form method="post" action="{%url 'chat_room:anonymous' %}">
                            <div class="switch">
                                <label>
                                  <input type="checkbox" name="anon_box" onchange="this.form.submit()" checked>
                                  <span class="lever"></span>
                                </label>
                            </div>
                            <input type="hidden" name="next" value="{{ request.path }}">
                        </form>
                    {% else %}
                        <span class="tooltiptext">Go Anonymous</span>
                        <form method="post" action="{%url 'chat_room:anonymous' %}">
                            <div class="switch">
                                <label>
                                  <input type="checkbox" name="anon_box" onchange="this.form.submit()">
                                  <span class="lever"></span>
                                </label>
                            </div>
                            <input type="hidden" name="next" value="{{ request.path }}">
                        </form>
                    {% endif %}
                </div>
                <div class="tooltip">
                    <span class="tooltiptext">Create Group Chat</span>
                    <a href="{% url 'chat_room:create-chatroom' %}" class="material-icons group-add button-color">
                        group_add
                    </a>
                </div>
            </div>
        </div>
        <div class="collection background-collection" style="border-color:#2c2f33;">
            {% for room in chatroom %}
                <div class="collection-item chatroom" style="padding:0; background-color:#35393d; color:#2c2f33; border-bottom:3px; border-style:solid;">
                    <a href="{% url 'chat_room:message-chatrooms' room.id %}" id="chat_room{{room.id}}" class="background-collection" style="background-color:#35393d; width:500px; border:none;">
                        <span class="title names" style="font-weight: bolder; color:#c1c9d6;">{{ room.name }}</span>
                    </a>
                    <div class="tooltip-container">
                        <div class="tooltip">
                            <span class="tooltiptext">Add User to Group</span>
                            <a href="{% url 'chat_room:add-to-group' room.id %}" class="material-icons person_add_alt button-color">
                                person_add_alt
                            </a>
                        </div>
                    </div>
                </div>
                    <!--  <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg" class="col s2"> -->
            {% endfor %}
        </div>
        <div class="background-title chatrooms">
            <h5 class="group-chat-label text-color">Direct Message</h5>
            <div class="tooltip-container">
                <div class="tooltip">
                    <span class="tooltiptext">Add User to List</span>
                    <a href="{% url 'Collegion_Backend:add-dm-user-form' %}" class="material-icons group-add button-color">
                        person_add_alt
                    </a>
                </div>
            </div>
        </div>
        <div id="dms" class="collection" style="border-color:#2c2f33;">
            {% for dm in direct_messages %}
            <a href="/chat/{{request.user.id}}/{{dm.id}}/" id="user${receiverId}" class="collection-item row" style="background-color:#35393d; color:#2c2f33; border-bottom:3px; border-style:solid;">
<!--                <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg" class="col s2">-->
                <div class="col s10">
                <span class="title" style="font-weight: bolder; color:#c1c9d6;">{{ dm.username }}</span>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    </div>
    <div class="col s9">
        <div class="card">
            {% if sender %}
            <div class="card background-title" style="margin:0px;">
                <div class="dmheader background-title">
                    <span class="title text-color" style="font-weight: bolder; margin-left: 1vw; font-size: 20px;">{{sender}}</span>
                </div>
            </div>
            {% elif group_name %}
            <div class="card background-title" style="margin:0px;">
                <div class="dmheader background-title">
                    <span class="title text-color" style="font-weight: bolder; margin-left: 1vw; font-size: 20px;">{{group_name}}</span>
                    <div class="pull-right" style="margin-right:1vw;">
                        <div class="tooltip-container">
                            <div class="tooltip">
                                <span class="tooltiptext">Add Member</span>
                                <a href="{% url 'chat_room:add-to-group' chatroom_id %}" class="material-icons button-color">
                                    person_add_alt
                                </a>
                            </div>
                            <div class="tooltip">
                                <span class="tooltiptext">Leave Group</span>
                                <a href="{% url 'chat_room:remove-from-group' chatroom_id %}" class="material-icons button-color">
                                    delete
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        <div id="board" class="section background-title scroller" style="height: 68vh; padding: 5px;">

            {% block content %}

            {% endblock %}

        </div>
        <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
            {% csrf_token %}
            <div class="row background-root">
                <div class="col s11">
                    <div class="input-field">
                        <input id="id_message" style="color:#c1c9d6;" name="message" type="text" placeholder="Type your message...">
                    </div>
                </div>
                <div class="col s1" style="line-height: 80px">
                    <button class="btn btn-floating waves-effect waves-light" style="background-color:#7289da;"><i class="material-icons">send</i></button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
</div>
{% load static %}

{% if is_chatroom %}
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        chatroom_id = "{{ chatroom_id }}";
        is_anonymous = "{{ anonymous_str }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send_chatroom("{{ request.user.username }}", "{{ request.user.profile.anonymous_name }}", '{{ chatroom_id }}', message.val(), is_anonymous);
                message.val('');
            })
        })
    </script>
{% else %}
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endif %}
{% endblock %}

templates/chat/create-chatroom.html
{% extends 'chat/chat.html' %}
{% block content %}


    <form method="post" id="create-chatroom-form" class="form-group">
        {% csrf_token %}
        <h3 class="text-color" style="margin-right:2px">Create Chatroom</h3>
        {% if not error == ""%}
            <div class="row chatroom-err">
                <p class="chatroom-err-msg">{{ error }}</p>
            </div>
        {% endif %}
        <div class="row">
            <div class="input-field col s12">
                <input name="name" id="id_name" type="text" class="validate">
                <label for="id_name" data-error="Group name already taken">Group Name</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <input type="submit" class="btn waves-effect waves-light right" name="btn-create" value="create">
            </div>
        </div>
<!--        <div class="row">-->
<!--            <input type="text" placeholder="Search by name, username" name="search" style="width: 210px">-->
<!--            <input type="submit" name="btn-search" class="btn btn-success" value="Search">-->
<!--        </div>-->
    </form>
{% endblock %}

templates/chat/index.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
        <link rel="stylesheet" href="{% static 'css/login-styles.css' %}">

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>
    <body class="background-root">
    {% block body %}
        <div class="section background-title">
            <div class="container white-text center-align text">
            <h2 style="color:#ffffff;">Collegion</h2>
            <p>Welcome to Collegion: Anonymous chatting</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    {% if error %}
                        <div class="errorbox">
                            <p class="error-msg">{{ error }}</p>
                        </div>
                    {% endif %}
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}" style="color:#7289da;">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>
  </html>

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block content %}

    {% for message in messages %}
        {% if message.anonymous %}
            {% if message.sender == request.user %}
            <div class="card-panel right" style="width: 75%; position: relative; background-color:#404ca1;">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder;" class="title text-color">{{ request.user.profile.anonymous_name }}</div>
                <span style="color:#c1c9d6;">{{ message }}</span>
            </div>
            {% else %}
            <div class="card-panel left background-collection " style="width: 75%; position: relative">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title text-color">{{ message.sender.profile.anonymous_name }}</div>
                <span style="color:#c1c9d6;">{{ message }}</span>
            </div>
            {% endif %}
        {% else %}
            {% if message.sender == request.user %}
            <div class="card-panel right" style="width: 75%; position: relative; background-color:#404ca1;">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title text-color">You</div>
                <span style="color:#c1c9d6;">{{ message }}</span>
            </div>
            {% else %}
            <div class="card-panel left background-collection" style="width: 75%; position: relative">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title text-color">{{ message.sender }}</div>
                <span style="color:#c1c9d6;">{{ message }}</span>
            </div>
            {% endif %}
        {% endif %}
    {% endfor %}

{% if is_chatroom %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,2000)
})
</script>
{% else %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,2000)
})
</script>
{% endif %}
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    {% csrf_token %}
    <form id="register-form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <label for="id_password_confirm" class="active">Confirm Password:</label>
            <input type="password" name="password_confirm" maxlength="128" required="" id="id_password_confirm">
        </p>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button type="submit" class="btn waves-effect waves-light pull-s12">Register</button>
            </div>
            </div>
        </div>
    </form>
    <script>
$(function () {
    $('#register-form').on('submit', function (event)
    {
        event.preventDefault();
        // Set variables
        var username = $('#id_username').val();
        var email = $('#id_email').val();
        var password = $('#id_password').val();
        let isEduEmail = /^[a-zA-Z0-9.!#$%&'*+=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[e][d][u](?:[e][d][u]{0,61}[a-zA-Z0-9])?)*$/;
        let matchedEmail = isEduEmail.test(email);
        // Implement guard clause for readability.
        if(username === '')
        {
            return alert("Please enter a username.");
        }
        // Check if password is entered
        if(password === '')
        {
            return alert("Please enter a valid password");
        }
        if(matchedEmail == false)
        {
            return alert("Please enter a valid email ending in .edu")
        }
        // Register user if passwords match
        if(password === $('#id_password_confirm').val())
        {
            register (username, email, password);
        }
        else
        {
            return alert("Please ensure your passwords are matching");
        }
    })
})
    </script>
{% endblock %}